biz_EN.md translated
vizplus/viz-biz pull request #1
Opened 2021-11-03 18:56 UTC by inov8ru

2021-11-04 10:34 UTC, chiliec requested changes

2021-11-04 10:34 UTC, chiliec commented on biz_EN.md
> +![первый пример](https://raw.githubusercontent.com/vizplus/viz-biz/main/1.jpg)
Why alternative text in russian?

2021-11-04 10:34 UTC, chiliec commented on biz_EN.md
> +# How can you create an unique business in VIZ?
"a unique", not "an"

2021-11-06 22:02 UTC, inov8ru commented on biz_EN.md
> +![первый пример](https://raw.githubusercontent.com/vizplus/viz-biz/main/1.jpg)
> Why alternative text in russian?

Fixed.

2021-11-06 22:02 UTC, inov8ru commented on biz_EN.md
> +# How can you create an unique business in VIZ?
Fixed.

2021-11-08 15:07 UTC, merged